phonotactics:
  language: "Proto Testa Mundi"
  structure: "CVC"
  sets: {
    C: [ "p","t","k","q","th","v","s","z","sh","zh","ch","x","h","pf","ts","m","n","ng","w","l","y" ],
    V: ["i","e","a","o","u"],
    T: [],
    N: []
  }
